"use client";

import { useActionState, useRef, useState } from "react";

import type { AccountWithBalance } from "../accounts/repo";
import { captureOwedExpenseAction, captureSplitExpenseAction } from "../app/split/actions";
import { NO_ERROR, type ActionState } from "../app/split/action-state";
import type { PersonWithBalance } from "../people/repo";

const INPUT = "rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100 placeholder:text-slate-500 focus:border-emerald-500 focus:outline-none";
const BUTTON = "rounded-md px-3 py-2 text-sm font-medium transition-colors disabled:opacity-50";

export function SplitForm({ people, categories, accounts, today }: { people: PersonWithBalance[]; categories: AccountWithBalance[]; accounts: AccountWithBalance[]; today: string }) {
  const [mode, setMode] = useState<"paid" | "owed">("paid");
  return <><div className="mb-6 flex border-b border-slate-800"><button type="button" onClick={() => setMode("paid")} className={`border-b-2 px-4 py-2 text-sm font-medium ${mode === "paid" ? "border-emerald-500 text-emerald-400" : "border-transparent text-slate-400 hover:text-slate-100"}`}>I paid</button><button type="button" onClick={() => setMode("owed")} className={`border-b-2 px-4 py-2 text-sm font-medium ${mode === "owed" ? "border-emerald-500 text-emerald-400" : "border-transparent text-slate-400 hover:text-slate-100"}`}>Someone else paid</button></div>{mode === "paid" ? <PaidForm people={people} categories={categories} accounts={accounts} today={today} /> : <OwedForm people={people} categories={categories} today={today} />}</>;
}

function PaidForm({ people, categories, accounts, today }: { people: PersonWithBalance[]; categories: AccountWithBalance[]; accounts: AccountWithBalance[]; today: string }) {
  const [selected, setSelected] = useState<Record<string, string>>({}); const [shareType, setShareType] = useState<"equal" | "exact">("equal"); const [notice, setNotice] = useState<string | null>(null); const formRef = useRef<HTMLFormElement>(null);
  const participants = Object.entries(selected).map(([personId, amount]) => shareType === "exact" ? { personId, amount } : { personId });
  const [state, submit, pending] = useActionState(async (previous: ActionState, form: FormData) => { const result = await captureSplitExpenseAction(previous, form); if (!result.error) { formRef.current?.reset(); setSelected({}); setNotice("Shared expense saved."); } return result; }, NO_ERROR);
  const ready = participants.length > 0 && categories.length > 0 && accounts.length > 0;
  function toggle(id: string, checked: boolean) { setSelected((current) => { const next = { ...current }; if (checked) next[id] = ""; else delete next[id]; return next; }); }
  return <form ref={formRef} action={submit} className="rounded-lg border border-slate-800 bg-slate-900/40 p-4"><input type="hidden" name="participants" value={JSON.stringify(participants)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Date"><input name="occurredAt" type="date" required defaultValue={today} className={INPUT} /></Field><Field label="Payee"><input name="payee" required placeholder="Where was it?" className={INPUT} /></Field><Field label="Total amount"><input name="amount" required inputMode="decimal" placeholder="0.00" className={INPUT} /></Field><Select label="Category" name="categoryId" items={categories} /><Select label="Paid from" name="accountId" items={accounts} /></div><div className="mt-5"><p className="text-sm text-slate-300">How should friends&apos; shares be calculated?</p><div className="mt-2 flex gap-4 text-sm text-slate-300"><label><input type="radio" checked={shareType === "equal"} onChange={() => setShareType("equal")} /> <span className="ml-2">Split evenly</span></label><label><input type="radio" checked={shareType === "exact"} onChange={() => setShareType("exact")} /> <span className="ml-2">Exact amounts</span></label></div><input type="hidden" name="shareType" value={shareType} /></div><fieldset className="mt-5"><legend className="text-sm text-slate-300">Friends</legend><div className="mt-2 space-y-2">{people.map((person) => <label key={person.id} className="flex flex-wrap items-center gap-3 text-sm text-slate-200"><input type="checkbox" checked={person.id in selected} onChange={(event) => toggle(person.id, event.target.checked)} /><span className="min-w-28">{person.name}</span>{shareType === "exact" && person.id in selected && <input required inputMode="decimal" value={selected[person.id]} onChange={(event) => setSelected((current) => ({ ...current, [person.id]: event.target.value }))} placeholder="Their share" className={`${INPUT} w-36`} />}</label>)}</div></fieldset>{state.error && <ErrorNote message={state.error} />}{notice && <p role="status" className="mt-4 text-sm text-emerald-300">{notice}</p>}<button type="submit" disabled={pending || !ready} className={`mt-5 ${BUTTON} bg-emerald-500 text-slate-950 hover:bg-emerald-400`}>{pending ? "Saving…" : "Save shared expense"}</button>{!ready && <p className="mt-3 text-sm text-amber-300">Choose at least one friend, a category, and an account.</p>}</form>;
}

function OwedForm({ people, categories, today }: { people: PersonWithBalance[]; categories: AccountWithBalance[]; today: string }) {
  const [notice, setNotice] = useState<string | null>(null); const formRef = useRef<HTMLFormElement>(null); const [state, submit, pending] = useActionState(async (previous: ActionState, form: FormData) => { const result = await captureOwedExpenseAction(previous, form); if (!result.error) { formRef.current?.reset(); setNotice("Shared expense saved."); } return result; }, NO_ERROR);
  return <form ref={formRef} action={submit} className="rounded-lg border border-slate-800 bg-slate-900/40 p-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Date"><input name="occurredAt" type="date" required defaultValue={today} className={INPUT} /></Field><Field label="Payee"><input name="payee" required placeholder="Where was it?" className={INPUT} /></Field><Field label="Your share"><input name="amount" required inputMode="decimal" placeholder="0.00" className={INPUT} /></Field><Select label="Category" name="categoryId" items={categories} /></div><fieldset className="mt-5"><legend className="text-sm text-slate-300">Who paid?</legend><div className="mt-2 space-y-2">{people.map((person) => <label key={person.id} className="block text-sm text-slate-200"><input required type="radio" name="personId" value={person.id} /> <span className="ml-2">{person.name}</span></label>)}</div></fieldset>{state.error && <ErrorNote message={state.error} />}{notice && <p role="status" className="mt-4 text-sm text-emerald-300">{notice}</p>}<button type="submit" disabled={pending || categories.length === 0} className={`mt-5 ${BUTTON} bg-emerald-500 text-slate-950 hover:bg-emerald-400`}>{pending ? "Saving…" : "Save expense"}</button>{categories.length === 0 && <p className="mt-3 text-sm text-amber-300">Create an expense category first.</p>}</form>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm text-slate-300">{label}{children}</label>; }
function Select({ label, name, items }: { label: string; name: string; items: AccountWithBalance[] }) { return <Field label={label}><select name={name} required defaultValue="" className={INPUT}><option value="" disabled>Choose {label.toLowerCase()}</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>; }
function ErrorNote({ message }: { message: string }) { return <p role="alert" className="mt-4 text-sm text-red-400">{message}</p>; }
